spring.application.name=Ticketworld
# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3307/mi_base
spring.datasource.username=mi_usuario
spring.datasource.password=mi_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Puerto de la app
server.port=8080