version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bdd_ticket
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_base
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
